#!/usr/bin/env bash
# shellcheck source=/dev/null
source './framework.sh'
# Check if the framework is installed
bootstrap_framework
#OO_LIB_IMPORTS
source './framework/index.sh'
namespace ethtpsctl
import util/log
Log::AddOutput ethtpsctl INFO
